### ISSUE TITLE
Add star

### ISSUE THREAD

**Issue by sas977** [kubernetes/features#302]
# Feature Description
- One-line feature description (can be used as a release note):
- Primary contact (assignee):
- Responsible SIGs:
- Design proposal link (community repo):
- Reviewer(s) - (for LGTM) recommend having 2+ reviewers (at least one from code-area OWNERS file) agreed to review. Reviewers from multiple companies preferred:
- Approver (likely from SIG/area to which feature belongs):
- Feature target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

**Comment by idvoretskyi** [comment]
@sas977 requires clarification.

**Comment by sas977** [comment]
@gnufied
